# Generated by Django 3.1.1 on 2020-09-13 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CveTable',
            fields=[
                ('no', models.IntegerField(db_column='No', primary_key=True, serialize=False)),
                ('platform', models.CharField(blank=True, db_column='Platform', max_length=30, null=True)),
                ('version', models.CharField(blank=True, db_column='Version', max_length=20, null=True)),
                ('platform_version', models.CharField(blank=True, db_column='Platform_Version', max_length=40, null=True)),
                ('platform_type', models.CharField(blank=True, db_column='Platform_Type', max_length=20, null=True)),
                ('vendor', models.CharField(blank=True, db_column='Vendor', max_length=20, null=True)),
                ('etc', models.CharField(blank=True, max_length=20, null=True)),
                ('up_date', models.CharField(blank=True, db_column='Up_date', max_length=20, null=True)),
                ('edition', models.CharField(blank=True, db_column='Edition', max_length=20, null=True)),
                ('language', models.CharField(blank=True, db_column='Language', max_length=20, null=True)),
                ('cve_id', models.CharField(blank=True, db_column='CVE_ID', max_length=30, null=True)),
                ('cwe_id', models.IntegerField(blank=True, db_column='CWE_ID', null=True)),
                ('n_of_exploits', models.IntegerField(blank=True, db_column='n_of_Exploits', null=True)),
                ('vulnerability_type', models.CharField(blank=True, db_column='Vulnerability_Type', max_length=20, null=True)),
                ('publish_year', models.IntegerField(blank=True, db_column='Publish_Year', null=True)),
                ('publish_date', models.CharField(blank=True, db_column='Publish_Date', max_length=20, null=True)),
                ('update_date', models.CharField(blank=True, db_column='Update_Date', max_length=20, null=True)),
                ('score', models.FloatField(blank=True, db_column='Score', null=True)),
                ('gained_access_level', models.CharField(blank=True, db_column='Gained_Access_Level', max_length=20, null=True)),
                ('access', models.CharField(blank=True, db_column='Access', max_length=20, null=True)),
                ('complexity', models.CharField(blank=True, db_column='Complexity', max_length=20, null=True)),
                ('authentication', models.CharField(blank=True, db_column='Authentication', max_length=30, null=True)),
                ('conf', models.CharField(blank=True, db_column='Conf', max_length=20, null=True)),
                ('integ', models.CharField(blank=True, db_column='Integ', max_length=20, null=True)),
                ('avail', models.CharField(blank=True, db_column='Avail', max_length=20, null=True)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=300, null=True)),
            ],
            options={
                'db_table': 'cve_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
    ]
